# Generated by Django 4.2.2 on 2023-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_products_workorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Inventory',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], max_length=100, null=True),
        ),
    ]
