# Generated by Django 4.2.2 on 2023-06-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_products_inventory_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.customer'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ready for pickup', 'ready for pickup'), ('pending', 'pending')], max_length=100, null=True),
        ),
    ]
