# Generated by Django 4.2.2 on 2023-06-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_workorder_customer_workorder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Accounts.customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('ready for pickup', 'ready for pickup')], max_length=100, null=True),
        ),
    ]
