# Generated by Django 4.2.2 on 2023-06-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_workorder_customer_alter_workorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='reference_no',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('ready for pickup', 'ready for pickup')], max_length=100, null=True),
        ),
    ]
