# Generated by Django 4.2.2 on 2023-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_customer_user_alter_inventory_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('ready for pickup', 'ready for pickup')], max_length=100, null=True),
        ),
    ]
