# Generated by Django 4.2.2 on 2023-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ready for pickup', 'ready for pickup'), ('pending', 'pending')], max_length=100, null=True),
        ),
    ]
