# Generated by Django 4.2.2 on 2023-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='spare_status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('requested', 'requested')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('repair in progress', 'repair in progress'), ('completed', 'completed'), ('pending', 'pending')], max_length=100, null=True),
        ),
    ]
