# Generated by Django 4.2.2 on 2023-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_inventory_quantity_workorder_spare_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='spare_status',
            field=models.CharField(choices=[('available', 'available'), ('requested', 'requested'), ('unavailable', 'unavailable')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('repair in progress', 'repair in progress'), ('completed', 'completed')], max_length=100, null=True),
        ),
    ]
